# Nayan Deployment file
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: {{ .Values.appName }}
  annotations:    
    app.kubernetes.io/Realease-Name: {{ .Release.Name }} 

    # Add Quote function
    app.kubernetes.io/Chart-Name: {{ quote .Chart.Name }}
    # Quote function
    app.kubernetes.io/Chart-Name: {{ .Chart.Name | quote }}
    # Pipeline
    app.kubernetes.io/Chart-Name: {{ .Chart.Name | upper }}
    app.kubernetes.io/Chart-Name: {{ .Chart.Name | lower }}
    # Default Function
    app.kubernetes.io/Release-Name: {{ default "MyDefault" .Values.releaseName | lower }}
    # Controlling Leading and Trailing White spaces 
    leading-whitespace: "   {{- .Chart.Name }}    Nayan"
    trailing-whitespace: "   {{ .Chart.Name -}}    Nayan"
    leadtrail-whitespace: "   {{- .Chart.Name -}}    Nayan" 
    # indent function
    indenttest: "  {{- .Chart.Name | indent 4 -}}  "
    # nindent function
    nindenttest: "  {{- indent 2 .Chart.Name | nindent 4 -}}  "  
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.imageName }}
          ports:
            - containerPort: 80
          resources:
{{- toYaml .Values.resources | nindent 12 -}}
